# Generated by Django 5.0.8 on 2024-10-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0026_acknowledgements'),
    ]

    operations = [
        migrations.AddField(
            model_name='transient',
            name='image_trim_status',
            field=models.CharField(default='not ready', max_length=20),
        ),
    ]
