# Generated by Django 5.0.8 on 2025-04-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0028_aperture_software_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLock',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_expires', models.DateTimeField()),
            ],
        ),
    ]
