# Generated by Django 5.0.8 on 2025-04-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0031_alter_status_ghost'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='photometric_redshift_err',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='redshift_err',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
