# Generated by Django 5.0.14 on 2025-06-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0033_update_acknowledgements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transient',
            options={'permissions': [
                ('upload_transient', 'Can launch a new transient workflow'),
                ('retrigger_transient', 'Can retrigger a transient workflow'),
                ('reprocess_transient', 'Can reprocess a transient workflow'),
            ]},
        ),
    ]
