# Generated by Django 5.0.14 on 2025-07-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0034_alter_transient_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageMetricsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_url', models.CharField(max_length=100)),
                ('request_method', models.CharField(max_length=10)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('submitted_data', models.TextField(blank=True, default='')),
                ('request_user', models.CharField(max_length=100)),
                ('request_ip', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='ExternalResourceCall',
        ),
    ]
