# Generated by Django 5.0.14 on 2025-07-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0035_usagemetricslogs_delete_externalresourcecall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagemetricslog',
            name='request_user',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='usagemetricslog',
            name='request_user_agent',
            field=models.CharField(blank=True, max_length=400, default=''),
        ),
    ]
