# Generated by Django 5.0.14 on 2025-07-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0035_usagemetricslogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalResourceCall',
        ),
    ]
