# Generated by Django 5.0.14 on 2025-07-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0035_usagemetricslogs_delete_externalresourcecall'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperture',
            name='workflow',
            field=models.CharField(blank=True, db_default='default', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aperturephotometry',
            name='workflow',
            field=models.CharField(blank=True, db_default='default', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='workflow',
            field=models.CharField(blank=True, db_default='default', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='workflow',
            field=models.CharField(blank=True, db_default='default', max_length=50, null=True),
        ),
    ]
