# Generated by Django 5.0.14 on 2025-07-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0036_usagemetricslog_request_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagemetricslog',
            name='request_user',
            field=models.CharField(max_length=150),
        ),
    ]
