# Generated by Django 5.1.12 on 2025-09-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0036_usagemetricslog_request_user_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalRequest',
        ),
    ]
