# Generated by Django 5.0.14 on 2025-07-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0036_usagemetricslog_request_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutout',
            name='fits',
        ),
        migrations.RemoveField(
            model_name='sedfittingresult',
            name='chains_file',
        ),
        migrations.RemoveField(
            model_name='sedfittingresult',
            name='model_file',
        ),
        migrations.RemoveField(
            model_name='sedfittingresult',
            name='percentiles_file',
        ),
        migrations.RemoveField(
            model_name='sedfittingresult',
            name='posterior',
        ),
        migrations.AddField(
            model_name='aperture',
            name='workflow',
            field=models.CharField(blank=True, db_default='workflow_default', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aperturephotometry',
            name='workflow',
            field=models.CharField(blank=True, db_default='workflow_default', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cutout',
            name='workflow',
            field=models.CharField(blank=True, db_default='workflow_default', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='workflow',
            field=models.CharField(blank=True, db_default='workflow_default', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='workflow',
            field=models.CharField(blank=True, db_default='workflow_default', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cutout',
            name='fits_exists',
            field=models.BooleanField(default=False),
        ),
    ]
