# Generated by Django 5.1.13 on 2025-10-21 20:21

import app.boto_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0037_delete_externalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutout',
            name='cutout_image',
            field=models.FileField(blank=True, null=True, storage=app.boto_storage.S3MediaStorage(), upload_to=''),
        ),
    ]
