# Generated by Django 5.1.14 on 2025-12-17 22:41

from django.db import migrations


def add_new_tasks(apps, schema_editor):
    Task = apps.get_model("host", "Task")
    for name in [
        'Crop transient images',
        'Generate thumbnails',
        'Generate thumbnails final',
    ]:
        Task(name=name).save()


def migrate_trim_status(apps, schema_editor):
    Transient = apps.get_model("host", "Transient")
    TaskRegister = apps.get_model("host", "TaskRegister")
    Task = apps.get_model("host", "Task")
    Status = apps.get_model("host", "Status")

    task = Task.objects.get(name__exact="Crop transient images")
    processed_status = Status.objects.get(message__exact="processed")
    not_processed_status = Status.objects.get(message__exact="not processed")
    for transient in Transient.objects.all():
        task_register, created = TaskRegister.objects.get_or_create(
            transient=transient,
            task=task,
            status=processed_status if transient.image_trim_status == "processed" else not_processed_status,
        )
        if not created:
            print(f'''WARNING: Unexpected TaskRegister object already exists for "{task.name}" '''
                  f'''with status "{task_register.status.message}".''')


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0038_alter_transient_name'),
    ]

    operations = [
        migrations.RunPython(add_new_tasks),
        migrations.RunPython(migrate_trim_status),
        migrations.RemoveField(
            model_name='transient',
            name='image_trim_status',
        ),
    ]

