# Generated by Django 5.1.14 on 2025-12-17 22:41

from django.db import migrations

NEW_TASK_NAMES = [
    'Crop transient images',
    'Generate thumbnail',
    'Generate thumbnail final',
    'Generate thumbnail SED local',
    'Generate thumbnail SED global',
]


def add_new_tasks(apps, schema_editor):
    '''Add the new workflow task definitions'''
    Task = apps.get_model("host", "Task")
    for task_name in NEW_TASK_NAMES:
        Task.objects.create(name=task_name)


def add_workflow_taskregisters(apps, schema_editor):
    '''Add task registers for the new tasks to existing transients so that they will run when retriggered.'''
    Transient = apps.get_model("host", "Transient")
    TaskRegister = apps.get_model("host", "TaskRegister")
    Task = apps.get_model("host", "Task")
    Status = apps.get_model("host", "Status")
    processed_status = Status.objects.get(message__exact="processed")
    not_processed_status = Status.objects.get(message__exact="not processed")

    all_transients = Transient.objects.all()
    all_trs = TaskRegister.objects.select_related('transient').select_related('task').all()
    num_transients = len(all_transients)
    for idx, transient in enumerate(all_transients):
        print(f'[{idx + 1}/{num_transients}] Adding thumbnail task registers for transient "{transient.name}"...')
        for task_name in NEW_TASK_NAMES:
            if not all_trs.filter(transient=transient, task__name=task_name):
                set_to_processed = task_name == 'Crop transient images' and transient.image_trim_status == "processed"
                task_register = TaskRegister.objects.create(
                    transient=transient,
                    task=Task.objects.get(name=task_name),
                    status=processed_status if set_to_processed else not_processed_status,
                )
            else:
                print(f'''WARNING: Unexpected TaskRegister object already exists for "{task_name}" '''
                      f'''with status "{task_register.status.message}".''')


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0039_remove_transient_information'),
    ]

    operations = [
        migrations.RunPython(add_new_tasks),
        migrations.RunPython(add_workflow_taskregisters),
        migrations.RemoveField(
            model_name='transient',
            name='image_trim_status',
        ),
    ]
