# Generated by Django 5.1.14 on 2026-01-29 22:32

import re
from django.db import migrations, models

def rename_bad_transients(apps, schema_editor):
    '''Rename the offending transients to use an underscore in their ID instead of a space'''
    Transient = apps.get_model("host", "Transient")
    all_transients = Transient.objects.all()
    bad_transients = []
    for transient in all_transients:
        if not bool(re.match(r"[-a-zA-Z0-9_[]+\Z", transient.name)):
            transient.display_name = transient.name
            transient.name = transient.name.replace(" ", "_")
            bad_transients.append(transient)

    Transient.objects.bulk_update(bad_transients, ["name", "display_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0040_add_new_workflow_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='transient',
            name='display_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.RunPython(rename_bad_transients)
    ]
