# Generated by Django 5.1.14 on 2025-12-17 22:41

from django.db import migrations


def add_new_tasks(apps, schema_editor):
    Task = apps.get_model("host", "Task")
    for name in [
        'Generate thumbnail SED local',
        'Generate thumbnail SED global',
    ]:
        Task(name=name).save()


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0040_remove_transient_information'),
    ]

    operations = [
        migrations.RunPython(add_new_tasks),
    ]
