# Generated by Django 5.1.14 on 2026-01-28 16:59

from django.db import migrations, models


def initialize_cropped(apps, schema_editor):
    '''Add task registers for the new tasks to existing transients so that they will run when retriggered.'''
    Transient = apps.get_model("host", "Transient")
    TaskRegister = apps.get_model("host", "TaskRegister")
    Cutout = apps.get_model("host", "Cutout")
    Status = apps.get_model("host", "Status")
    not_processed_status = Status.objects.get(message__exact="not processed")
    # Collect all objects and filter later for efficiency
    all_transients = Transient.objects.all()
    all_trs = TaskRegister.objects.all()
    all_cutouts = Cutout.objects.all()
    num_transients = len(all_transients)
    for idx, transient in enumerate(all_transients):
        print(f'[{idx + 1}/{num_transients}] Initializing Cutout.cropped value for transient "{transient.name}"...')
        crop_trs = all_trs.filter(transient=transient, task__name='Crop transient images')
        if not crop_trs:
            continue
        crop_tr = crop_trs[0]
        # Consider all cutouts "cropped" if the cropping task has any status except "not processed". This may
        # cause some image files to be re-downloaded unnecessarily from source catalogs when the transient is
        # reprocessed, but it should prevent the possibility of a cropped image being treated as original source data.
        probably_cropped = crop_tr.status != not_processed_status
        for cutout in all_cutouts.filter(transient=transient):
            cutout.cropped = probably_cropped
            cutout.save()


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0040_add_new_workflow_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutout',
            name='cropped',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.RunPython(initialize_cropped),
    ]
