# Generated by Django 5.1.14 on 2026-01-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0041_cutout_cropped'),
    ]

    operations = [
        migrations.AddField(
            model_name='transient',
            name='display_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
