# Generated by Django 5.1.14 on 2026-02-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0045_delete_taskregistersnapshot_alter_transient_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acknowledgement',
        ),
    ]
