# Generated by Django 5.1.14 on 2026-02-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0046_delete_acknowledgement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogphotometry',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='catalogphotometry',
            name='filter',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='CatalogPhotometry',
        ),
    ]
