# Generated by Django 5.1.14 on 2026-04-22 21:28

from django.db import migrations, models

def copy_logage_to_age(apps, schema_editor):
    """Copy over the value in the log_age columns to the newly created age columns 
    (see https://github.com/scimma/blast/issues/330)"""
    SEDFittingResult = apps.get_model("host", "SEDFittingResult")
    all_sed_res = SEDFittingResult.objects.all()
    for sed_res in all_sed_res:
        sed_res.age_16 = sed_res.log_age_16
        sed_res.age_50 = sed_res.log_age_50
        sed_res.age_84 = sed_res.log_age_84
        sed_res.save()



class Migration(migrations.Migration):

    dependencies = [
        ('host', '0047_remove_catalogphotometry_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedfittingresult',
            name='age_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='age_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='age_84',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(copy_logage_to_age)
    ]
