# Generated by Django 5.1.14 on 2026-04-29 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0048_sedfittingresult_age_16_sedfittingresult_age_50_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='catalog_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='catalog_release',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='object_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transient',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transient',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='host.host')
        ),
    ]
