# Generated by Django 5.1.14 on 2026-05-11 17:22

import django.db.models.deletion
import host.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0049_host_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=64, unique=True, validators=[host.models.Alias.validate_name])),
                ('host', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE,
                                           to='host.host')),
                ('transient', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE,
                                                to='host.transient')),
            ],
        ),
    ]
