# Generated by Django 5.1.14 on 2026-07-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0050_add_alias_alter_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transient',
            name='update_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transient',
            name='update_fields',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
