# Generated by Django 5.1.14 on 2026-06-16 05:41

import django.db.models.deletion
import host.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0050_add_alias_alter_host_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostSpectrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('DESI', 'DESI'), ('SDSS', 'SDSS'), ('BOSS', 'BOSS'), ('NED', 'NED')], max_length=20)),
                ('spectrum_file', models.FileField(blank=True, null=True, upload_to=host.models.spectrum_file_path)),
                ('wavelength_min_angstrom', models.FloatField(blank=True, null=True)),
                ('wavelength_max_angstrom', models.FloatField(blank=True, null=True)),
                ('redshift', models.FloatField(blank=True, null=True)),
                ('spectrum_id', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('software_version', models.CharField(blank=True, max_length=50, null=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.host')),
                ('transient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.transient')),
            ],
        ),
    ]
