# Generated by Django 5.1.14 on 2026-06-25 22:09

import django.db.models.deletion
import host.models
from django.db import migrations, models

HOST_SPECTRUM_DOWNLOAD_TASK_NAME = 'Host spectrum download'
HOST_SPECTRUM_THUMBNAIL_TASK_NAME = 'Generate thumbnail host spectrum'


def add_host_spectrum_task(apps, schema_editor):
    '''Add the new Host spectrum download task definition'''
    Task = apps.get_model("host", "Task")
    Status = apps.get_model("host", "Status")
    Task.objects.create(name=HOST_SPECTRUM_DOWNLOAD_TASK_NAME)
    Status.objects.create(message='no host spectrum', type='error')


def add_host_spectrum_taskregisters(apps, schema_editor, new_task_name=''):
    add_spectrum_taskregisters(apps, schema_editor, new_task_name=HOST_SPECTRUM_DOWNLOAD_TASK_NAME)


def add_thumbnail_spectrum_task(apps, schema_editor):
    '''Add the new Generate thumbnail host spectrum task definition'''
    Task = apps.get_model("host", "Task")
    Task.objects.create(name=HOST_SPECTRUM_THUMBNAIL_TASK_NAME)


def add_thumbnail_spectrum_taskregisters(apps, schema_editor, new_task_name=''):
    add_spectrum_taskregisters(apps, schema_editor, new_task_name=HOST_SPECTRUM_THUMBNAIL_TASK_NAME)


def add_spectrum_taskregisters(apps, schema_editor, new_task_name=''):
    '''Add task registers for the new task to existing transients so that they will run when retriggered.'''
    Transient = apps.get_model("host", "Transient")
    TaskRegister = apps.get_model("host", "TaskRegister")
    Task = apps.get_model("host", "Task")
    Status = apps.get_model("host", "Status")
    not_processed_status = Status.objects.get(message__exact="not processed")
    task = Task.objects.get(name=new_task_name)

    all_transients = Transient.objects.all()
    all_trs = TaskRegister.objects.select_related('transient').select_related('task').all()
    num_transients = len(all_transients)
    for idx, transient in enumerate(all_transients):
        print(f'[{idx + 1}/{num_transients}] Adding "{HOST_SPECTRUM_THUMBNAIL_TASK_NAME}" '
              f'task register for transient "{transient.name}"...')
        if not all_trs.filter(transient=transient, task=task):
            TaskRegister.objects.create(
                transient=transient,
                task=task,
                status=not_processed_status,
            )
        else:
            print(f'''WARNING: Unexpected TaskRegister object already exists for "{new_task_name}" '''
                  f'''on transient "{transient.name}".''')


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0051_transient_update_comment_transient_update_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostSpectrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('DESI', 'DESI'), ('SDSS', 'SDSS'), ('BOSS', 'BOSS'), ('NED', 'NED')], max_length=20)),  # noqa
                ('spectrum_file', models.FileField(blank=True, null=True, upload_to=host.models.spectrum_file_path)),
                ('wavelength_min_angstrom', models.FloatField(blank=True, null=True)),
                ('wavelength_max_angstrom', models.FloatField(blank=True, null=True)),
                ('redshift', models.FloatField(blank=True, null=True)),
                ('ra_deg', models.FloatField(blank=True, null=True)),
                ('dec_deg', models.FloatField(blank=True, null=True)),
                ('spectrum_id', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('software_version', models.CharField(blank=True, max_length=50, null=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.host')),  # noqa
                ('transient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.transient')),  # noqa
            ],
        ),
        migrations.RunPython(add_host_spectrum_task),
        migrations.RunPython(add_thumbnail_spectrum_task),
        migrations.RunPython(add_host_spectrum_taskregisters),
        migrations.RunPython(add_thumbnail_spectrum_taskregisters),
    ]
