# Generated by Django 5.1.14 on 2026-06-25 22:09

from django.db import migrations

DOWNLOAD_TASK_NAME = 'Host spectrum download'
THUMBNAIL_TASK_NAME = 'Generate thumbnail host spectrum'


def add_host_spectrum_task(apps, schema_editor):
    '''Add the new Host spectrum download task definition'''
    Task = apps.get_model("host", "Task")
    Status = apps.get_model("host", "Status")
    Task.objects.create(name=DOWNLOAD_TASK_NAME)
    Status.objects.create(message='no host spectrum', type='error')


def add_thumbnail_spectrum_task(apps, schema_editor):
    '''Add the new Generate thumbnail host spectrum task definition'''
    Task = apps.get_model("host", "Task")
    Task.objects.create(name=THUMBNAIL_TASK_NAME)


def add_spectrum_taskregisters(apps, schema_editor, new_task_name=''):
    '''Add task registers for the new task to existing transients so that they will run when retriggered.'''
    Transient = apps.get_model("host", "Transient")
    TaskRegister = apps.get_model("host", "TaskRegister")
    Task = apps.get_model("host", "Task")
    Status = apps.get_model("host", "Status")
    not_processed_status = Status.objects.get(message__exact="not processed")

    all_transients = Transient.objects.all()
    all_trs = TaskRegister.objects.select_related('transient').select_related('task').all()
    num_transients = len(all_transients)
    task = {}
    task[DOWNLOAD_TASK_NAME] = Task.objects.get(name=DOWNLOAD_TASK_NAME)
    task[THUMBNAIL_TASK_NAME] = Task.objects.get(name=THUMBNAIL_TASK_NAME)
    for idx, transient in enumerate(all_transients):
        for new_task_name in [DOWNLOAD_TASK_NAME, THUMBNAIL_TASK_NAME]:
            print(f'[{idx + 1}/{num_transients}] Adding task register for transient "{transient.name}": '
                  f'"{new_task_name}"...')
            if not all_trs.filter(transient=transient, task=task[new_task_name]):
                TaskRegister.objects.create(
                    transient=transient,
                    task=task[new_task_name],
                    status=not_processed_status,
                )
            else:
                print(f'''WARNING: Unexpected TaskRegister object already exists for "{new_task_name}" '''
                      f'''on transient "{transient.name}".''')


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0052_hostspectrum'),
    ]

    operations = [
        migrations.RunPython(add_host_spectrum_task),
        migrations.RunPython(add_thumbnail_spectrum_task),
        migrations.RunPython(add_spectrum_taskregisters),
    ]
