# Generated by Django 5.2.16 on 2026-09-16 21:43

import django.db.models.deletion
import host.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0054_usagemetricslog_and_alias_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperture',
            name='dec_deg',
            field=models.FloatField(help_text='Declination in decimal degrees e.g., 60.123424'),
        ),
        migrations.AlterField(
            model_name='aperture',
            name='ra_deg',
            field=models.FloatField(help_text='Right Ascension in decimal degrees e.g., 132.34564'),
        ),
        migrations.AlterField(
            model_name='aperture',
            name='software_version',
            field=models.CharField(blank=True, help_text='Version of Blast that generated this object', max_length=50, null=True),  # noqa
        ),
        migrations.AlterField(
            model_name='aperturephotometry',
            name='software_version',
            field=models.CharField(blank=True, help_text='Version of Blast that generated this object', max_length=50, null=True),  # noqa
        ),
        migrations.AlterField(
            model_name='cutout',
            name='software_version',
            field=models.CharField(blank=True, help_text='Version of Blast that generated this object', max_length=50, null=True),  # noqa
        ),
        migrations.AlterField(
            model_name='host',
            name='dec_deg',
            field=models.FloatField(help_text='Declination in decimal degrees e.g., 60.123424'),
        ),
        migrations.AlterField(
            model_name='host',
            name='milkyway_dust_reddening',
            field=models.FloatField(blank=True, help_text='transient E(B-V) e.g, 0.2', null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='photometric_redshift',
            field=models.FloatField(blank=True, help_text='photometric redshift', null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='photometric_redshift_err',
            field=models.FloatField(blank=True, help_text='photometric redshift error', null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='ra_deg',
            field=models.FloatField(help_text='Right Ascension in decimal degrees e.g., 132.34564'),
        ),
        migrations.AlterField(
            model_name='host',
            name='redshift',
            field=models.FloatField(blank=True, help_text='redshift e.g., 0.01', null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='redshift_err',
            field=models.FloatField(blank=True, help_text='redshift error', null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='software_version',
            field=models.CharField(blank=True, help_text='Version of Blast that generated this object', max_length=50, null=True),  # noqa
        ),
        migrations.AlterField(
            model_name='hostspectrum',
            name='software_version',
            field=models.CharField(blank=True, help_text='Version of Blast that generated this object', max_length=50, null=True),  # noqa
        ),
        migrations.AlterField(
            model_name='sedfittingresult',
            name='software_version',
            field=models.CharField(blank=True, help_text='Version of Blast that generated this object', max_length=50, null=True),  # noqa
        ),
        migrations.AlterField(
            model_name='starformationhistoryresult',
            name='software_version',
            field=models.CharField(blank=True, help_text='Version of Blast that generated this object', max_length=50, null=True),  # noqa
        ),
        migrations.AlterField(
            model_name='transient',
            name='dec_deg',
            field=models.FloatField(help_text='Declination in decimal degrees e.g., 60.123424'),
        ),
        migrations.AlterField(
            model_name='transient',
            name='host',
            field=models.ForeignKey(blank=True, help_text='host associated with the transient', null=True, on_delete=django.db.models.deletion.SET_NULL, to='host.host'),  # noqa
        ),
        migrations.AlterField(
            model_name='transient',
            name='name',
            field=models.CharField(help_text='unique transient name, e.g., 2022abc', max_length=64, unique=True, validators=[host.models.Transient.validate_name]),  # noqa
        ),
        migrations.AlterField(
            model_name='transient',
            name='processing_status',
            field=models.CharField(default='processing', help_text='processing status of the transient dataset.\n                        * "processed" - transient has been complement processed and all data\n                          should be present in the science payload.\n                        * "processing" - transient is still processing this transient and\n                          some parts of the science payload may not be populated at the current time.\n                        * "blocked" - this transient has not been successfully fully processed\n                          and some parts of the science payload will not be populated.', max_length=20),  # noqa
        ),
        migrations.AlterField(
            model_name='transient',
            name='progress',
            field=models.IntegerField(default=0, help_text='Percentage of the transient workflow that has been completed.'),  # noqa
        ),
        migrations.AlterField(
            model_name='transient',
            name='ra_deg',
            field=models.FloatField(help_text='Right Ascension in decimal degrees e.g., 132.34564'),
        ),
        migrations.AlterField(
            model_name='transient',
            name='software_version',
            field=models.CharField(blank=True, help_text='Version of Blast that generated this object', max_length=50, null=True),  # noqa
        ),
        migrations.AlterField(
            model_name='transient',
            name='spectroscopic_class',
            field=models.CharField(blank=True, help_text='spectroscopic classification, if any', max_length=20, null=True),  # noqa
        ),
        migrations.AlterField(
            model_name='transient',
            name='update_comment',
            field=models.CharField(blank=True, help_text='A brief explanation for why the transient data were updated', max_length=500, null=True),  # noqa
        ),
        migrations.AlterField(
            model_name='transient',
            name='update_fields',
            field=models.CharField(blank=True, help_text='Transient database fields that were last updated.', max_length=500, null=True),  # noqa
        ),
    ]
